name: docs
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.8
  - pip
  - ipykernel
  - ipython
  - setuptools
  - sphinx
  - sphinx-copybutton
  - numpydoc
  # - pip:
  #     - -e ../..
